Repository COSC481W-2024Winter/Fictionary-Frontend, pull requests merged in 2024-02, with the labels that each got.

#6 Ellen/pages
  package-lock.json
  package.json
  src/App.js
  src/Categories.js
  src/Results.js
  src/Scoreboard.js
Labels: frontend

#22 Add: Dynamic Rendering for User Interface in Room.js
  package-lock.json
  package.json
  src/Categories.js
  src/Drawing.js
  src/Guest.js
  src/Home.js
  src/Host.js
  src/Lobby.js
  src/Results.js
  src/Room.js
  src/Scoreboard.js
  src/Voting.js
  tailwind.config.js
Labels: Scope: frontend, Sprint 1, UI, Game logic

#24 Add: Testing Dynamic Rendering for User Interface in Room.js
  package-lock.json
  package.json
  src/App.test.js
  src/Home.js
  src/Results.js
  src/Room.test.js
  src/Scoreboard.js
Labels: Scope: frontend, testing, Sprint 1, UI, Game logic

#25 Update: Rules Page
  .env
  src/Rules.js
  src/index.css
Labels: documentation, Scope: frontend, Sprint 1, UI
