Repository COSC481W-2024Winter/Fictionary-Frontend, pull requests merged in 2024-04, with the labels that each got.

#64 Update and Add: Updated the Rules page and added Pictures to the Rules page.
  src/Pictures/Artist-Drawing.png
  src/Pictures/Category_Select.png
  src/Pictures/Scores.png
  src/Pictures/Trick_Voting.png
  src/Pictures/Tricksters-Guess.png
  src/Rules.js
Labels: documentation, enhancement, Scope: frontend, Sprint 3

#66 frontend: add function 'submitGuesses' to Drawing page and 'changeGuesses' to Voting page
  src/Drawing.js
  src/Lobby.js
  src/Results.js
  src/Room.js
  src/Scoreboard.js
  src/Voting.js
  src/__tests__/Room.test.js
Labels: Scope: frontend, Sprint 3, Feature, UI, Game logic

#65 fix: players continuing
  src/Categories.js
  src/Drawing.js
  src/Results.js
  src/Scoreboard.js
  src/Voting.js
  src/index.css
Labels: bug, enhancement, Scope: frontend, Sprint 3, Game logic

#71 frontend: modify the methods 'submitGuess' and 'changeGuesses'
  src/Drawing.js
  src/Results.js
  src/Room.js
  src/Voting.js
Labels: Scope: frontend, Sprint 3, Feature, UI, Game logic

#68 Feature: Added UI and Frontend Functions for Chat Functionality
  src/Drawing.js
Labels: Scope: frontend, Sprint 3, Feature

#73 add: display drawings on multiple pages
  src/Drawing.js
  src/Results.js
  src/Voting.js
Labels: enhancement, Scope: frontend, Sprint 3, UI, Game logic

#75 Fix: Fixed the ArtArray to show when page loads.
  src/Rules.js
Labels: enhancement, Scope: frontend, UI

#76 Substitute placeholders in voting and results page
  src/Drawing.js
  src/Results.js
  src/Voting.js
Labels: Scope: frontend, Sprint 3, UI, Game logic
