Repository COSC481W-2024Winter/Fictionary-Frontend, pull requests merged in 2024-03, with the labels that each got.

#38 Fix: start button and blanking out bug
  .gitignore
  package-lock.json
  package.json
  src/Categories.js
  src/Drawing.js
  src/Guest.js
  src/Host.js
  src/Lobby.js
  src/Results.js
  src/Room.js
  src/Scoreboard.js
  src/Voting.js
  src/__tests__/Room.test.js
  tailwind.config.js
Labels: Scope: frontend, testing, Sprint 2, UI, Game logic

#39 Fix: timer
  src/Categories.js
  src/Drawing.js
  src/Lobby.js
  src/Room.js
  src/Voting.js
  src/__tests__/Timer.test.js
Labels: Scope: frontend, Sprint 2, UI, Game logic

#41 Fix: rendering Lobby.js
  src/Lobby.js
Labels: Scope: frontend, Sprint 2, UI, Game logic

#44 Fix - frontend tests
  src/Lobby.js
  src/__tests__/Room.test.js
Labels: Scope: frontend, testing, Sprint 2

#45 frontend: modified 'Results.js' and 'Scoreboard.js' to display updates to scores
  src/Lobby.js
  src/Results.js
  src/Room.js
  src/Scoreboard.js
  src/__tests__/Room.test.js
Labels: Scope: frontend, Sprint 2, Status: Blocked, Feature, UI

#48 Added: Canvas Functionality/Canvas Customization
  package-lock.json
  package.json
  src/Drawing.js
  src/Room.js
Labels: Scope: frontend, Sprint 2, Feature, UI

#50 Add: Category logic to make requests to backend (category logic/fetching)
  package-lock.json
  src/Categories.js
  src/Room.js
  src/__tests__/Category.test.js
Labels: Scope: frontend, Sprint 2, Game logic
